name: Keepalive Workflow

on:
  schedule:
    - cron: '0 0 1 * *'   # 每月1号自动运行一次
  workflow_dispatch:       # 允许你在网页上随时手动点击运行

permissions:
  contents: write

jobs:
  cronjob-keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
